import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Quizo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex-col">
            <div>
              <h1>Quizzo</h1>
              <Link href={'/'}>Home</Link>
              <Link href={'/About'}>About</Link>
            </div>
            <div>
              <Link href={'/Login'}>Login</Link>
            </div>
        </header>
        {children}
      </body>
    </html>
  );
}
