# Generated by Django 4.2.6 on 2024-03-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='correctoption',
            field=models.IntegerField(default=0),
        ),
    ]
