# Generated by Django 4.2.6 on 2024-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_havegiven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_correct', 'Single Correct'), ('paragraph_type', 'Paragraph Type'), ('integer_type', 'Integer Type')], default='single_correct', max_length=20),
        ),
        migrations.AlterField(
            model_name='userresponsequiz',
            name='user_response',
            field=models.TextField(default=''),
        ),
    ]
